"""empty message

Revision ID: 8d3236f92402
Revises: b00e854fbf9d
Create Date: 2020-04-25 05:30:16.622117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d3236f92402'
down_revision = 'b00e854fbf9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userbalance', 'balance',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userbalance', 'balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
