"""empty message

Revision ID: b00e854fbf9d
Revises: 
Create Date: 2020-04-25 04:40:12.376401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00e854fbf9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paid_by', sa.String(), nullable=True),
    sa.Column('split_with', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userbalance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1', sa.String(), nullable=True),
    sa.Column('user2', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbalance')
    op.drop_table('expenses')
    # ### end Alembic commands ###
