"""empty message

Revision ID: ed2745c85f7c
Revises: 5c419f460d0d
Create Date: 2020-05-02 12:23:56.158820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2745c85f7c'
down_revision = '5c419f460d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_id')
    # ### end Alembic commands ###
